# Internal configuration file; do not touch
# This file contains options that are not in the config by default

generic-message-listener:
    blacklist: true
    events: [
        "org.spongepowered.api.event.GrantAchievementEvent$TargetPlayer",
        "org.spongepowered.api.event.AdvancementEvent$Grant",
        "org.spongepowered.api.event.MessageChannelEvent$Chat",
        "org.spongepowered.api.event.DestructEntityEvent$Death",
        "org.spongepowered.api.event.ClientConnectionEvent$Join",
        "org.spongepowered.api.event.ClientConnectionEvent$Disconnect"
    ]
