bot:
    # Bot token; Never share this with anyone
    # Don't know where to find this? Please see the Installation instructions on the plugin page
    token: "token"
    # The bot's prefix for running commands on Discord
    # Example: "!"
    prefix: ">"
    game:
        # The game the bot is playing
        # Example: "Minecraft"
        name: "Addison lay back"
        # 0 = Playing; 1 = Streaming; 2 = Listening to; 3 = Watching
        type: 3

channels:
    # channel_name: "channel_id"
    #
    # Default channel: global
    # Plugin channel format: "plugin:channel"
    #
    # Example:
    # channels:
    #     global: "137421286501646336"
    #     "nucleus:staff": "464155898030587905"
    channels:
        global: "id"
    # Console channel's id
    # Example: "137722245853347840"
    console_channel_id: "id"

plugin:
    # Should BungeeCord be used for account linking
    use_remote_linking: false

generic-message-listener:
    # Whether or not generic channel messages (/me, /say etc.) should be enabled
    enabled: false

# Enables the debugger; Don't touch this unless you need to
debug: false
